- hosts: wowza18
  tasks:
   - name: Run script tracking status code
     script: /etc/ansible/script/wowza-edge/checker_status.sh
     register: status
     failed_when: "'FAILED' in status.stderr"


 
   - debug:
      var: status.stdout_lines

   - name: Send Notifications
     telegram:
        token: "513434634:AAHhFY8i_vgavxEFI5cPfEro0_A1ore8gc4"
        chat_id: 233570604
        msg: "Hostname: {{ ansible_hostname }}\nUse ' restart {{ansible_hostname }} ' cmd to restart server"
     when: status.stdout == "1\r\n"
   
