 - hosts: wowza-edge
   vars_prompt:
    - name: "app_name"
      prompt: "Input App Name:  "
      private: no

   tasks:

    - name: Synchronization of src on the control machine to dest on the remote hosts
      synchronize:
       src: /etc/ansible/config/wowza-edge/app/{{app_name}}/
       dest: /usr/local/WowzaStreamingEngineEdge1/content/{{app_name}}/
       delete: yes




