#- hosts: wowza-edge
- hosts: wowza18
  tasks:       
  - name: Kill process Java
    shell: pkill -9 java
    register: cmdln
    failed_when: "cmdln.rc == 2"

  - name: Comment file hosts 
    script: /etc/ansible/script/wowza-edge/comment.sh
    notify:
      - start wowzaEdge


  handlers:
  - name: start wowzaEdge
    service:
      name: WowzaStreamingEngineEdge1
      state: restarted
