- hosts: "{{name_server}}"
  tasks: 
  - name: Kill process Java
    shell: pkill -9 java
    register: cmdln
    failed_when: "cmdln.rc == 2"

  - name: Comment file hosts
    script: /etc/ansible/script/wowza-edge/comment.sh
    notify:
      - restart wowzaEdge

  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30


  - name: Check again Wowza-Edge
    script: /etc/ansible/playbooks/wowza-edge/telegram/check_status.sh
    register: status

  - name: Uncomment file hosts
    script: /etc/ansible/script/wowza-edge/uncomment.sh
    when: status.stdout == "0\r\n"
  
  - name: Send Notifications
    telegram:
        token: "513434634:AAHhFY8i_vgavxEFI5cPfEro0_A1ore8gc4"
        chat_id: 233570604
        msg: "Hostname: Done Restart {{ name_server }}\nUsername: {{ ansible_user }}"
    when: status.stdout == "0\r\n"

  - name: Send Notifications
    telegram:
        token: "513434634:AAHhFY8i_vgavxEFI5cPfEro0_A1ore8gc4"
        chat_id: 233570604
        msg: "Hostname:  Restart Error {{ name_server }}\nUsername: {{ ansible_user }}"
    when: status.stdout == "1\r\n"

 
 
  handlers:
  - name: restart wowzaEdge
    service:
      name: WowzaStreamingEngineEdge1
      state: restarted

