- hosts: local

  vars:
    user_name:

      - name: phatnk2
        key: "{{ lookup('file', '/etc/ansible/config/ssh/phatnk2.pub') }}"

      - name: thanhnx
        key: "{{ lookup('file', '/etc/ansible/config/ssh/thanhnx.pub') }}"

      - name: vuonghq3
        key: "{{ lookup('file', '/etc/ansible/config/ssh/vuonghq3.pub') }}"

      - name: quangnd38
        key: "{{ lookup('file', '/etc/ansible/config/ssh/quangnd38.pub') }}"

      - name: thuannd9
        key: "{{ lookup('file', '/etc/ansible/config/ssh/thuannd9.pub') }}"

      - name: tuanna69
        key: "{{ lookup('file', '/etc/ansible/config/ssh/tuanna69.pub') }}"
  tasks:

    - name: "Create user account"
      user:
        name: "{{ item.name }}"
      with_items: "{{ user_name }}"

    - name: Add ssh pub keys
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ user_name }}"

    - name: Allow 'User' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{ item.name }}'
        line: '{{ item.name }}          ALL=(ALL)       NOPASSWD: ALL'
        validate: visudo -cf %s
      with_items: "{{ user_name }}"

