- hosts: dev-Ads

  vars:
    nginx_binary_name: "nginx"
    nginx_service_name: "{{nginx_binary_name}}"
    nginx_installation_type: "packages"
    nginx_installation_types_using_service: ["packages", "configuration-only"]
    nginx_daemon_mode: "on"

  tasks:
    - name: Clone source
      copy:
          src: /etc/ansible/package
          dest: /root/
      with_items:
         - libmaxminddb-1.2.0-1.el7.x86_64.rpm
         - luajit-2.0.4-3.el7.x86_64.rpm
         - nginx-1.12.1-1.el7.centos.ngx.x86_64.rpm


    - name: Install RPM Package
      command: rpm -Uvh /root/{{ item }}
      args:
        warn: no
      with_items:
         - libmaxminddb-1.2.0-1.el7.x86_64.rpm
         - luajit-2.0.4-3.el7.x86_64.rpm
         - nginx-1.12.1-1.el7.centos.ngx.x86_64.rpm


    - name: Clone source For Nginx Configuations
      copy:
          src: /etc/ansible/package
          dest: /etc/nginx/
      with_items:
         - maxmind-city.mmdb
         - maxmind-country.mmdb

    - name: Clone configuations for Nginx.conf
      template:
         src: /etc/ansible/config/nginx.conf
         dest: /etc/nginx/nginx.conf
         owner: root
         group: root
         mode: 0644
      notify:
         - restart nginx


    - name: Clone configuations for site Nginx
      copy:
         src: /etc/ansible/config/proxy/
         dest: /etc/nginx/conf.d/
         directory_mode: yes
      notify:
        - reload nginx

  handlers:
    - name: restart nginx
      debug: msg="checking config first"
      changed_when: True
      notify:
        - check nginx configuration
        - restart nginx - after config check

    - name: reload nginx
      debug: msg="checking config first"
      changed_when: True
      notify:
        - check nginx configuration
        - reload nginx - after config check

    - name: check nginx configuration
      command: "{{ nginx_binary_name }} -t"
      register: result
      changed_when: "result.rc != 0"
      check_mode: no
      when: nginx_installation_type in nginx_installation_types_using_service

    - name: restart nginx - after config check
      service: name={{ nginx_service_name }} state=restarted
      when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"

    - name: reload nginx - after config check
      service: name={{ nginx_service_name }} state=reloaded
      when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"

- import_playbook: /etc/ansible/playbooks/notify.yaml 
