- name: Clone configuations for Nginx.config
  template:
    src: /etc/ansible/config/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Clone configuations for site {{file_name}}
  template:
    src: /etc/ansible/config/proxy/{{ file_name }}
    dest: /etc/nginx/conf.d/
  notify:
     - reload nginx

- name: Send test message
  telegram:
    token: "513434634:AAHhFY8i_vgavxEFI5cPfEro0_A1ore8gc4"
    chat_id: 233570604
    msg: "Ansible update  Configuration {{ file_name }}"


#- name: Synchronization of src on the control machine to dest on the remote hosts
#      synchronize:
#       src: /etc/ansible/config/proxy/
#       dest: /etc/nginx/conf.d/ 
#       delete: yes

